### ISSUE TITLE
Update UI Design

### ISSUE THREAD

**Issue by tiffany352** [tiffany352/Roblox-Tag-Editor#13]
AC
- More material design overall
- Improved tag menu
- Show indicator arrows on groups for expanded/collapsed
- Make visibility and settings buttons actually look like buttons

**Comment by Quenty** [comment]
I think the design should stay close to Roblox studio's UI design, especially if it's mapped to a plugin component.

**Comment by tiffany352** [comment]
With the design changes I have in mind, I want to bring the design closer to native-studio feeling, rather than further away. In particular, more recently designed parts like the insert object menu.

**Comment by tiffany352** [comment]
Fixed by #43
