### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Kampfkarren** [tiffany352/Roblox-Tag-Editor#37]
Roblox Studio has added dark theme, and Tag Editor has not yet added a check for this. It makes the plugin stand out way too much.

![](https://cdn.discordapp.com/attachments/142706044416688128/459884677604311051/unknown.png)

**Comment by tiffany352** [comment]
I have a branch with a WIP version of theming: https://github.com/tiffany352/Roblox-Tag-Editor/tree/themes
