### ISSUE TITLE
Color picker not responsive

### ISSUE THREAD

**Issue by chess123mate** [tiffany352/Roblox-Tag-Editor#50]
Tag colours cannot be changed through the "Change color" menu - not through clicking on the colour picker nor through typing in new colours in the text boxes.

**Comment by general-adhoc** [comment]
@chess123mate did you ever find a workaround to this problem?

Also, is this tool still being worked on or has someone else picked up maintenance?

**Comment by RuizuKun-Dev** [comment]
> @chess123mate did you ever find a workaround to this problem?
> 
> Also, is this tool still being worked on or has someone else picked up maintenance?

you can find the tag Color value inside of ServerStorage and change that instead.

**Comment by tiffany352** [comment]
Should be fixed in the latest update.

https://github.com/tiffany352/Roblox-Tag-Editor/releases/tag/v2.1.1

Sorry it took me over a year to fix it.
