### ISSUE TITLE
"New tag editor version coming online; unloading the old version"

### ISSUE THREAD

**Issue by EYYCHEEV** [tiffany352/Roblox-Tag-Editor#51]
![Screen Shot 2020-05-18 at 10 40 14 PM](https://user-images.githubusercontent.com/24510019/82288987-95588680-9958-11ea-84eb-28d372b3bf91.png)

Thanks for the great plugin. I get this message every time I have done testing a game. Should I just ignore it, or it tells me to upgrade the plugin to the latest version?

**Comment by umustbeloggedintododat** [comment]
this happens too much for me

**Comment by RuizuKun-Dev** [comment]
Can this be removed please?

**Comment by RuizuKun-Dev** [comment]
@tiffany352 Can this be removed please?
[All you have to do this comment this line](https://github.com/tiffany352/Roblox-Tag-Editor/blob/fc5e19517ce3cd41e073c817e1fdfeac98ca258c/src/Main.lua#L84)

**Comment by tiffany352** [comment]
https://github.com/tiffany352/Roblox-Tag-Editor/releases/tag/v2.1.1

I just put out a new update which fixes this. Sorry it took so long to get around to it.
