### ISSUE TITLE
How to assign tags

### ISSUE THREAD

**Issue by FirstVertex** [tiffany352/Roblox-Tag-Editor#53]
Sorry for such a basic question, but the instructions never say how to assign a tag to a mesh.

Can you please break it down for me?  I can CREATE a tag but I can never ASSIGN it.  Please, it seems like I'm missing some fundamental knowledge that everyone else seems to have.  I don't want to tag at runtime with script, I thought this plugin would allow me to tag at design time in Studio?

**Comment by FirstVertex** [comment]
I ended up using the Roblox command bar to type in commands to assign tags to parts

`game.CollectionService:AddTag(game.Workspace.Cylinder, 'MaintainParts')`

I thought the purpose of this Plugin was to provide GUI for such actions?  Forgive me if I misunderstood.

**Comment by tiffany352** [comment]
![image](https://user-images.githubusercontent.com/1254344/104394438-7916e480-54fb-11eb-9a57-884649c75c3d.png)

Select the object you want to apply a tag to, and then click on the tag in the window. When it's highlighted in blue like this, it means the object has the tag applied to it. You can click on it when it's blue to remove the tag.

Sorry that this isn't clear.

**Comment by Anaminus** [comment]
I had trouble with this, too. Adding some sort of checkbox to the UI might help make this more discoverable.
