### ISSUE TITLE
World View is erroring upon opening

### ISSUE THREAD

**Issue by Git0uttaHere** [tiffany352/Roblox-Tag-Editor#57]
![Issue](https://user-images.githubusercontent.com/36766130/143725155-1dfa4beb-2186-48ae-a375-2f576fa21894.png)
Not sure why. Everything else seems to work fine.

**Comment by tiffany352** [comment]
The only way I've figured out to reproduce this is to have two tags with the same name in ServerStorage.TagList. Does your place have something similar?

I've put out a new version which has a fix for the case I ran into. Let me know if the fix works for you as well.

**Comment by Git0uttaHere** [comment]
Yes, for some reason it generated 2 of the same tag. Seems like it's fixed now though, tyvm.
