### ISSUE TITLE
Plugin causes Studio to show saving dialog window, even though no changes were made

### ISSUE THREAD

**Issue by nidmb** [tiffany352/Roblox-Tag-Editor#64]
The plugin causes Studio to show the saving dialog window when attempting to close the place.
It creates a waypoint (`Migrating tags folder`) in ChangeHistoryService right after opening the place, despite no changes being made.
This does not happen if the TagList folder does not exist (aka plugin has never been used on given place).

**Comment by tiffany352** [comment]
I put out a quick update with a fix for this, shouldn't happen anymore. Thanks for reporting it.

**Comment by hs458gh** [comment]
how to edit profile in roblox
