### ISSUE TITLE
Support highlight effect in world view

### ISSUE THREAD

**Issue by tiffany352** [tiffany352/Roblox-Tag-Editor#65]
![image](https://user-images.githubusercontent.com/1254344/179299137-c599e66f-bd6a-4f03-9176-4fea71a10606.png)

Can be put into the CoreGui so it doesn't pollute the workspace. Should be added as a new visualization mode.

**Comment by sasial-dev** [comment]
Even consider switching all the modes (box, outline) to highlight!
